// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//SHA1 Checksum:	8a8aac48cfc97d1607d3a3c20eeb09a7a81f8c09 

using System;
using Google.GData.Client;
using Google.GData.Extensions;
using Google.GData.Spreadsheets;
namespace DBAndFileAccess
{
	public class GoogleSheetReader
	{
		public GoogleSheetReader ()
		{
		}
	}
}

